### ISSUE TITLE
Subtasks are kicked out of the parent task when adding multiple tasks

### ISSUE THREAD

**Issue by davidskeck** [mrvladus/Errands#130]
Hello,

I am running Errands 45.1.2 and I have noticed that when I add multiple subtasks to a parent, the subtasks are kicked out of the parent. I am attaching a video to show what is occurring.

Thank you for a lovely app!

[Screencast from 2024-01-02 22-32-47.webm](https://github.com/mrvladus/Errands/assets/1740630/b5895127-50c8-4ef5-ae89-f6e6bfa61d1f)

**Comment by mrvladus** [comment]
@davidskeck Hi! Do you use sync? If so can you post terminal output?

**Comment by davidskeck** [comment]
Hello! I do use sync. Here's the terminal output when I recreate the example above.

```
[DEBUG] Sync: Getting tasks from remote
/app/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'caldav.fastmail.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[DEBUG] Sync: Getting tasks from remote
/app/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'caldav.fastmail.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[DEBUG] Sync: Update local task from remote: 5b0196ee-8014-46a7-a680-262a2eed86ff
[DEBUG] Sync: Create new task on remote: 0efe5fb2-57c2-4f0a-a0d9-4c951d78385f
/app/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'caldav.fastmail.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[DEBUG] Sync: Getting tasks from remote
/app/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'caldav.fastmail.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[DEBUG] Sync: Getting tasks from remote
/app/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'caldav.fastmail.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[DEBUG] Sync: Getting tasks from remote
/app/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'caldav.fastmail.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[DEBUG] Sync: Getting tasks from remote
/app/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'caldav.fastmail.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[DEBUG] Lists: Update UI...
[DEBUG] Task list 93f8dd86-daeb-4b2b-9cf7-5408ea501c01: Update UI
[DEBUG] Task list f92e57bf-fbde-4ac1-b93c-a969eb217fb6: Update UI
[DEBUG] Task list 789c826f-2e50-4ed4-834b-ffbc7516c806: Update UI
[DEBUG] Task list 1429dd86-314c-472d-b1d4-c28483352e65: Update UI
[DEBUG] Task list 277e499c-7cfd-41b2-bb85-b92a95efd143: Update UI
[DEBUG] Task list 8098953b-4aa4-4437-976f-5ff048e36f57: Update UI
[DEBUG] Task list 33b5cf1b-b2c0-43b0-acdb-c23ade9d219a: Update UI
[DEBUG] Task list: change parent for 5b0196ee-8014-46a7-a680-262a2eed86ff
[INFO] Add task: 5b0196ee-8014-46a7-a680-262a2eed86ff
[DEBUG] Details: Update info
```

**Comment by rubenmvc** [comment]
I checked this issue because I would like to start contributing to GNOME Circle projects like this, specially from an app I really like :)

The thing is that I'm trying to reproduce this issue over the current main commit (2024/1/20, version 45.1.6) using Builder. Is there any precondition that I need to know to achieve this behavior or the bug was already fixed in previous versions and the ticket could be closed?
[Screencast from 2024-01-20 22-49-23.webm](https://github.com/mrvladus/Errands/assets/32852022/a2ae1b60-e3d5-43ef-870a-e372c6b03195)

**Comment by mrvladus** [comment]
Is this bug still present? Because there was some sync improvements since.

**Comment by davidskeck** [comment]
Yes, I can verify this still occurs in version 45.1.8.

**Comment by mrvladus** [comment]
Is bug still present in last version? I still can't replicate this.

**Comment by davidskeck** [comment]
I can confirm the issue is still present in `46.0.5`.

**Comment by mrvladus** [comment]
Does Fastmail allow sub-tasks at all?

**Comment by mrvladus** [comment]
Because Google for example does not, but it still uses CalDAV.

**Comment by davidskeck** [comment]
That's a really good question. I don't know how to check since I can't even view my tasks in the Fastmail website. I would guess they maybe don't? But when I add the task back as a subtask, it does stay. It is just always kicked out at first.

**Comment by mmuenn** [comment]
I can replicate this bug using Mailcow with SOGo as a CalDav Server.

The issue seems to be that Errands uploads some ical properties with underscores instead of hyphens, including the RELATED-TO property that is used to mark the relation between a subtask and its parent task.

The problem is the way calendar.save_todo uses the kwargs syntax to parse ical values. Obviously you cannot specify hyphenated parameter names directly, but using a dict instead works.

Replacing line 452 of ./errands/lib/sync/providers/caldav.py  with the following fixes this issue for me:

~~~
            new_todo = calendar.save_todo( **{
                "categories": ",".join(task.tags) if task.tags else None,
                "description" : task.notes,
                "dtstart" :(
                    datetime.datetime.fromisoformat(task.start_date)
                    if task.start_date
                    else None
                ),
                "due": (
                    datetime.datetime.fromisoformat(task.due_date)
                    if task.due_date
                    else None
                ),
                "priority": task.priority,
                "percent-complete": task.percent_complete,
                "related-to": task.parent,
                "summary": task.text,
                "uid": task.uid,
                "x-errands-color": task.color,
                "x-errands-expanded": int(task.expanded),
                "x-errands-toolbar-shown": int(task.toolbar_shown),
            })
~~~

**Comment by mrvladus** [comment]
Added in a0f7f9ae320ad4ac88e58cdd3517c4283d69fb81. I'll make a release and we can test it.

**Comment by mrvladus** [comment]
Pushed update to Flathub, when it'll arrive, please, test it and tell if it's working.

**Comment by davidskeck** [comment]
This is absolutely great!! The issue is fixed flawlessly for me. Thank you @mrvladus and @mmuenn!! This makes Errands so much nicer for me. :smile:
