### ISSUE TITLE
CalDAV: RELATED-TO doesn't get set when dragging a task into another to make it a subtask

### ISSUE THREAD

**Issue by smithfred** [mrvladus/Errands#303]
With a CalDAV backend, when creating a subtask in Errands, the RELATED-TO field in the CalDAV VTODO is set to the ID of the parent task to indicate the relationship (as Apple Calendar does).

However, if a task is created and then dragged into another task to make it a subtask, the field does not get set correctly.

**Comment by mrvladus** [comment]
Is it fixed in the last update?

**Comment by smithfred** [comment]
Radicale with Errands 46.2.1, but there were more serious problems with the sync logic that led me to stop using Errands for now to avoid data loss.

**Comment by mrvladus** [comment]
It's not working well with radicale servers.

**Comment by tocto** [comment]
Hallo, i have a similar problem: When i am syncing with caldav my Subtask will be created as separate tasks. 

This occures espacially once  i ad a new subtask and the sync process starts. If i disable the sync, add subtask and enable it afterwards. The task with all subtask will still exist in the app. But on my caldav server there will be created separate tasks. Hence there is probaly a bug in the sync progress.
